### ISSUE TITLE
Inconsistent capitalisation on data type list

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#81]
Some terms are all lower case (genetic data, spectrometry, protein data) and most others are capitalised. Would be good to have them all the same (Capitalised seems better).

![Screen Shot 2020-03-25 at 1 31 18 PM](https://user-images.githubusercontent.com/49563305/78179377-f2829200-7415-11ea-8071-7a42ceb381c8.png)

**Comment by NicolasKieffer** [comment]
I can't reproduce this bug. Data looks fine on my instance.
_(Those data depend of dataseer-ml web service, it's not stored locally anymore)_

![image](https://user-images.githubusercontent.com/16922410/79168407-1c5e9000-7dea-11ea-819f-54a1171cc3cf.png)

_(@kermitt2 restart dataseer-web process should fix this bug)_

**Comment by kermitt2** [comment]
(re-started on dataseer-dev.science-miner.com)

**Comment by kermitt2** [comment]
There is one issue here still present I think. 

dataseer-ml is making prediction at the first level of the data type taxonomy. It means that it can predict as types `spectrometry` and `protein data` which are parent types with children, but with no Wiki page on their own. 
When these 2 types are predicted they don't have Wiki information, in particular no `label` field with the expected spelling (with capital letter) as the others. So they will always appear in the list in lower case, without any textual description and without a correct link to the Wiki.  

I think to correct this, there is no other way than having a Wiki page for each of these 2 data types. Even if they are not "end data types", they can be predicted (and we can't predict their subtypes for the moment due to lack of training data at subtype levels here).

**Comment by timvines19** [comment]
There are pages for Protein Data (https://wiki.dataseer.io/doku.php?id=data_type:protein_data) and Spectrometry (https://wiki.dataseer.io/doku.php?id=data_type:spectrometry) on the wiki

**Comment by kermitt2** [comment]
Yes indeed so I don't understand why it's not working. 

The following gives the correct data type information (same for dataseer-ml-dev):
> curl -GET http://cloud.science-miner.com/dataseer-ml/service/jsonDataTypes

```
    "protein data": {
        "mesh_id": "68011506",
        "url": "http://wiki.dataseer.io/doku.php?id=data_type:Protein%20Data",
        "label": "Protein Data",
        "molecular sequence annotation": {
            "description": "The addition of descriptive information about the function or structure of a molecular sequence to its molecular sequence data record.",
            "mesh_id": "D058977",
            "url": "http://wiki.dataseer.io/doku.php?id=data_type:Protein%20Data%3AMolecular%20Sequence%20Annotation",
            "label": "Molecular Sequence Annotation",
            "count": 3
        },
        "protein conformation": {
            "description": "The characteristic 3-dimensional shape of a protein, including the secondary, supersecondary (motifs), tertiary (domains) and quaternary structure of the peptide chain.",
...
```

We see for `protein data` that we have the correct label information: `Protein Data` for display and the right url, but this is wrong in the UI.

![Screenshot](https://user-images.githubusercontent.com/2340795/80797216-8c6a6580-8ba1-11ea-800c-6840ee957dcb.png)

@NicolasKieffer could you have a look ?

**Comment by NicolasKieffer** [comment]
It's working locally (on master).

![Capture d’écran de 2020-05-01 15-55-11](https://user-images.githubusercontent.com/16922410/80810625-8f2a8200-8bc4-11ea-8036-f1207e9dcaed.png)

Maybe refresh cache will resolve it? (Maj +F5)

**Comment by kermitt2** [comment]
Refreshing the cache had no effect, but restarting the web app had refreshed the resource apparently and the menu is now up to date too. Probably triggering by hand a resync (as annotator") would have worked too. 

So ok it works, but I will keep an eye on it after each redeployment :)
